spring.application.name=MyProject

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/simple_register_login_system
spring.datasource.username=root
spring.datasource.password=""

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080